<a href="https://colab.research.google.com/github/def-himani/MachineLearning/blob/main/Basics/Numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Numerical python

+ Faster than usual python lists
+ Can perform lots of mathematical operations in it

## Testing speed of list and numpy arrays

In [1]:
from time import process_time

In [3]:
# LIST
py_list = [i for i in range(10000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

0.00046957599999997157


In [6]:
import numpy as np

In [ ]:
# NUMPY Array
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()


print(end_time - start_time)

0.007956130999996702


In [9]:
# numpy array dimension

np_array = np.array([(1,2,3),(4,4,6)])
np_array.shape

(2, 3)

In [12]:
#  set a data type
a = np.array([(1,2,3), (4,5,6)], dtype = float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
# Placeholders - 0s

np_zeros = np.zeros((3,3))
print(np_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Placeholder - 1s

np_ones = np.ones((3,2))
print(np_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
# Placeholder - Full

np_full = np.full((4,2), 5)
print(np_full)

[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [22]:
# Identity Matrix

i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
# Random Variable -> Default is float

r = np.random.random((2,2))
print(r)

[[0.7471355  0.91425762]
 [0.40623418 0.13425677]]


In [28]:
# Rand Int within a range of 10 and 20 ===> matrix dim: 2x3

r = np.random.randint(10,20,(2,3))
print(r)

[[11 15 16]
 [15 10 15]]
