<a href="https://colab.research.google.com/github/def-himani/MachineLearning/blob/main/Basics/Numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Numerical python

+ Faster than usual python lists
+ Can perform lots of mathematical operations in it

## Testing speed of list and numpy arrays

In [1]:
from time import process_time

In [3]:
# LIST
py_list = [i for i in range(10000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

0.00046957599999997157


In [6]:
import numpy as np

In [ ]:
# NUMPY Array
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()


print(end_time - start_time)

0.007956130999996702


In [9]:
# numpy array dimension

np_array = np.array([(1,2,3),(4,4,6)])
np_array.shape

(2, 3)

In [12]:
#  set a data type
a = np.array([(1,2,3), (4,5,6)], dtype = float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
# Placeholders - 0s

np_zeros = np.zeros((3,3))
print(np_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Placeholder - 1s

np_ones = np.ones((3,2))
print(np_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
# Placeholder - Full

np_full = np.full((4,2), 5)
print(np_full)

[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [22]:
# Identity Matrix

i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
# Random Variable -> Default is float

r = np.random.random((2,2))
print(r)

[[0.7471355  0.91425762]
 [0.40623418 0.13425677]]


In [28]:
# Rand Int within a range of 10 and 20 ===> matrix dim: 2x3

r = np.random.randint(10,20,(2,3))
print(r)

[[11 15 16]
 [15 10 15]]


In [34]:
# Evenly spaced random values ===> know how many values you want b/w x and y
# Stop value is considered

a = np.linspace(10, 30, 6)
print(a)

# Evenly spaced random values ===> know the step size you want (here 5) b/w x and y
# stop value is not included here

b = np.arange(10, 30, 5)
print(b)

[10. 14. 18. 22. 26. 30.]
[10 15 20 25]


In [36]:
# Convert list to numpy array

list1 = [1,2,3]
np_a = np.asarray(list1)
print(np_a)

[1 2 3]


## Numpy Array Inspection

In [37]:
a = np.random.randint(0, 10, (4,5))
print(a)

[[7 8 5 0 4]
 [3 4 7 6 3]
 [6 4 9 0 2]
 [3 5 1 5 7]]


In [38]:
a.shape

(4, 5)

In [39]:
a.ndim

2

In [40]:
a.size

20

In [41]:
a.dtype

dtype('int64')

## Array Operation

In [47]:
a = np.random.randint(1, 5, (2,2))
b = np.random.randint(1, 5, (2,2))

print(a, '\n\n', b)

[[1 2]
 [4 3]] 

 [[3 3]
 [1 4]]


In [48]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[4 5]
 [5 7]]
[[-2 -1]
 [ 3 -1]]
[[ 3  6]
 [ 4 12]]
[[0.33333333 0.66666667]
 [4.         0.75      ]]


## Array Manipulation

In [49]:
# Transpose
a = np.random.randint(1, 5, (2,2))
print(a)

[[2 2]
 [3 1]]


In [51]:
t = np.transpose(a)
print(t)

[[2 3]
 [2 1]]


In [52]:
# Another way to transpose

print(a.T)

[[2 3]
 [2 1]]


In [66]:
# Reshape an array (2,8) ==> (4,4)
# As long as the array size (here 16) remains same, we can reshape to any dimentions

a = np.random.randint(1, 8, (2,8))
print(a)

r1 = a.reshape(4,4)

print(r)


r2 = a.reshape(1,16)

print(r2)


[[2 3 5 7 7 3 2 7]
 [6 4 1 2 4 2 7 1]]
[[3 1 4 1]
 [4 3 2 3]
 [4 3 3 3]
 [3 2 4 3]]
[[2 3 5 7 7 3 2 7 6 4 1 2 4 2 7 1]]
